Add an example config panel
devosoft/cookiecutter-empirical-project pull request #36
Opened 2021-06-21 20:41 UTC by lemniscate8

Adding a configuration panel and some infrastructure to demonstrate use

2021-06-22 23:17 UTC, lemniscate8 commented
Looks like there's some problem with `<script src="https://cdn.jsdelivr.net/npm/less" ></script>` that's messing up styling and have yet to identity if it's due to recent changes.

2021-06-24 22:23 UTC, mmore500 requested changes
A few minor stylistic/cosmetic changes, otherwise looking good!

2021-06-24 22:23 UTC, mmore500 commented on {{cookiecutter.project_slug}}/include/{{cookiecutter.project_slug}}/ProjectConfig.hpp
> +  VALUE(HOLD_MAYO, bool, true, "Whether or not to hold the mayo"),
love it

2021-06-24 22:23 UTC, mmore500 commented on {{cookiecutter.project_slug}}/include/{{cookiecutter.project_slug}}/ProjectConfig.hpp
> +EMP_BUILD_CONFIG( {{ cookiecutter.project_name.replace(' ', '') }}Config,
use cookiecutter.project_slug

2021-06-24 22:23 UTC, mmore500 commented on {{cookiecutter.project_slug}}/include/{{cookiecutter.project_slug}}/ProjectConfig.hpp
> +EMP_BUILD_CONFIG( {{ cookiecutter.project_name.replace(' ', '') }}Config,
?

2021-06-24 22:23 UTC, mmore500 commented on {{cookiecutter.project_slug}}/include/{{cookiecutter.project_slug}}/ProjectConfig.hpp
> +EMP_BUILD_CONFIG( {{ cookiecutter.project_name.replace(' ', '') }}Config,
would need to change this everywhere else

2021-06-24 22:23 UTC, mmore500 commented on {{cookiecutter.project_slug}}/include/{{cookiecutter.project_slug}}/ProjectConfig.hpp
> +EMP_BUILD_CONFIG( {{ cookiecutter.project_name.replace(' ', '') }}Config,
oh, better: put an object `Config` inside of namespace `project_slug`

2021-06-24 22:23 UTC, mmore500 commented on {{cookiecutter.project_slug}}/include/{{cookiecutter.project_slug}}/example.hpp
> +void SetupProjectConfig({{ cookiecutter.project_name.replace(' ', '') }}Config & config)  {
rename so it's clear this is web entry point and one below is native entry point

2021-06-24 22:23 UTC, mmore500 commented on {{cookiecutter.project_slug}}/include/{{cookiecutter.project_slug}}/example.hpp
> +void AddExistingConfig({{ cookiecutter.project_name.replace(' ', '') }}Config & config, emp::ArgManager & am) {
I would put config stuff into its own header `config_setup.hpp` and make free functions `snake_case`

2021-06-24 22:23 UTC, mmore500 commented on {{cookiecutter.project_slug}}/source/native.cpp
>    std::cout << "Hello, world!" << std::endl;
we should switch std::endl for '\n'

2021-06-24 22:23 UTC, mmore500 commented on {{cookiecutter.project_slug}}/source/native.cpp
> +  // Set up a configuration panel for native application
Print config settings

2021-06-24 22:23 UTC, mmore500 commented on {{cookiecutter.project_slug}}/source/web.cpp
> +  // An example to show config usage
Can you tell a little about what the example is supposed to do?

2021-06-24 22:23 UTC, mmore500 commented on {{cookiecutter.project_slug}}/source/web.cpp
> +UI::TextArea example_area;
This can go into the scope of main

2021-06-29 01:26 UTC, mmore500 approved these changes
looks good. a few comments. We should be able to merge once we exorcise that segfault.

2021-06-29 01:26 UTC, mmore500 commented on {{cookiecutter.project_slug}}/include/{{cookiecutter.project_slug}}/config_setup.hpp
> +  if(std::filesystem::exists("{{cookiecutter.project_slug}}.cfg")) {
space after if

2021-06-29 01:26 UTC, mmore500 commented on {{cookiecutter.project_slug}}/include/{{cookiecutter.project_slug}}/example.hpp
> +  std::cout << "example thing!" << "\n";
use `'\n'`

2021-06-29 01:26 UTC, mmore500 commented on {{cookiecutter.project_slug}}/source/native.cpp
> +  std::cout << "Hello, world!" << "\n";
ibid

2021-06-29 21:57 UTC, merged